export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
      // <link rel="preconnect" href="https://fonts.googleapis.com"/>
      // <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
      // <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap" rel="stylesheet"/>
        <html lang="en">
          <body>{children}</body>
        </html>
    )
}
