import "../index.css"
import { Space_Grotesk } from 'next/font/google'
import Navbar from './components/NavBar'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
const grotesk = Space_Grotesk({ subsets: ['latin'], variable: 'grotesk' })

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={grotesk.className} >
      <body>
        <Navbar />
        {children}</body>
    </html>
  )
}
